# coding: utf-8

"""
    Catalog Next API.

    This documentation describes the Catalog Next API for all versions and other miscellaneous endpoints.  # noqa: E501

    OpenAPI spec version: 1.16.3+dcs
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dcs_catalog_client
from dcs_catalog_client.models.external_tracker import ExternalTracker  # noqa: E501
from dcs_catalog_client.rest import ApiException


class TestExternalTracker(unittest.TestCase):
    """ExternalTracker unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExternalTracker(self):
        """Test ExternalTracker"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dcs_catalog_client.models.external_tracker.ExternalTracker()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
