# coding: utf-8

"""
    Catalog Next API.

    This documentation describes the Catalog Next API for all versions and other miscellaneous endpoints.  # noqa: E501

    OpenAPI spec version: 1.16.3+dcs
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import dcs_catalog_client
from dcs_catalog_client.models.catalog_v3_pivoted import CatalogV3Pivoted  # noqa: E501
from dcs_catalog_client.rest import ApiException


class TestCatalogV3Pivoted(unittest.TestCase):
    """CatalogV3Pivoted unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCatalogV3Pivoted(self):
        """Test CatalogV3Pivoted"""
        # FIXME: construct object with mandatory attributes with example values
        # model = dcs_catalog_client.models.catalog_v3_pivoted.CatalogV3Pivoted()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
